version: '2'
services:
  ui:
    build: ./ui
    ports:
      - '3000:3000'
    stdin_open: true # docker run -i, important to run react app
    # tty: true      # docker run -t
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8080:8080'